# Generated by Django 2.1.15 on 2022-12-08 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20221208_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
